/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.kyngs.libby.plugin;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibbyGradlePluginTest {
    @Test void pluginRegistersATask() {
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("xyz.kyngs.libby.plugin.greeting");

    }
}
